import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {validateUnit,LocalContentProvider} from '../src/content.js';import {evaluate} from '../src/exercise.js';import {newGame} from '../src/store.js';import {record,mastery,chooseQuestion,unitReady} from '../src/learning.js';import {addXp,chest,item,maxHp} from '../src/economy.js';import {startBattle,attack} from '../src/combat.js';import {toggle,tick} from '../src/timer.js';
const unit=JSON.parse(fs.readFileSync(new URL('../content/calculo/calculo-demo.json',import.meta.url)));
test('contenido y detección de JSON inválido',()=>{assert.deepEqual(validateUnit(unit),[]);assert.ok(validateUnit({...unit,exercises:[{id:'malo'}]}).length>0);assert.throws(()=>JSON.parse('{error'))});
test('evaluación exacta y numérica con coma',()=>{assert.equal(evaluate(unit.exercises[0],'7').ok,true);assert.equal(evaluate(unit.exercises[0],'5').ok,false);assert.equal(evaluate({type:'numeric',answer:1.5,tolerance:.01},'1,501').ok,true)});
test('dominio no aumenta por repetir el mismo ejercicio el mismo día',()=>{const s=newGame();const q=unit.exercises[0];record(s,unit,q,true,8);const a=mastery(s,unit).percent;const second=record(s,unit,q,true,8);assert.equal(second.qualified,false);assert.equal(mastery(s,unit).percent,a);assert.ok(chooseQuestion(s,unit));assert.equal(unitReady(s,unit),false)});
test('progresión, cofres e inventario equipable',()=>{const s=newGame();addXp(s,100);assert.ok(s.level>1);const reward=chest(s);assert.ok(reward.gold||item(reward.id));assert.ok(maxHp(s)>0)});
test('combate por turnos y daño eventual',()=>{const s=newGame();startBattle(s);const hp=s.battle.hp;for(let i=0;i<20&&s.battle.hp===hp;i++)attack(s,true,'strike',2);assert.ok(s.battle.hp<hp);assert.ok(s.battle.turn>0)});
test('temporizador pasa a descanso al terminar',()=>{const t=newGame().timer;toggle(t);t.endsAt=Date.now()-1000;assert.equal(tick(t),true);assert.equal(t.phase,'break');assert.equal(t.remaining,600)});

test('proveedor aísla JSON roto y acepta unidad MD',async()=>{const original=globalThis.fetch;const md='\x60\x60\x60json\n'+JSON.stringify({...unit,id:'unidad-md'})+'\n\x60\x60\x60';globalThis.fetch=async path=>({ok:true,status:200,json:async()=>({files:['./calculo/roto.json','./calculo/unidad-md.md']}),text:async()=>path.endsWith('roto.json')?'{mal':md});try{const p=await new LocalContentProvider().load();assert.equal(p.units.length,1);assert.equal(p.errors.length,1);assert.match(p.errors[0],/roto.json/)}finally{globalThis.fetch=original}});
