import {demoUnits} from './demo-fallback.js';
import {SUBJECTS} from './config.js';
const TYPES=['multiple-choice','true-false','short','numeric','written','predict-code','complete-code','debug-code','logic','puzzle','timed'];
const slug=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export class LocalContentProvider{
 constructor(){this.units=[];this.errors=[]}
 async load(){this.units=[];this.errors=[];let files=[];try{const r=await fetch('./content/manifest.json',{cache:'no-cache'});if(!r.ok)throw Error(`HTTP ${r.status}`);const manifest=await r.json();if(!Array.isArray(manifest.files))throw Error('manifest.files debe ser una lista');files=manifest.files}catch(e){this.errors.push(`Falta content/manifest.json (${e.message}). Se cargó la demo incorporada; sube la carpeta content completa para añadir unidades.`);this.units=demoUnits.map(u=>structuredClone(u));return this}
 for(const path of files){try{if(typeof path!=='string'||!/^\.\/((calculo|fisica|programacion|bases-de-datos)\/[a-z0-9-]+\.(json|md))$/.test(path))throw Error('Ruta de contenido no válida');const res=await fetch(`./content/${path.slice(2)}`,{cache:'no-cache'});if(!res.ok)throw Error(`HTTP ${res.status}`);let raw=await res.text();if(path.endsWith('.md')){const match=raw.match(/```json\s*([\s\S]*?)\s*```/i);if(!match)throw Error('El MD debe contener un bloque ```json con una unidad completa');raw=match[1]}const unit=JSON.parse(raw);const err=validateUnit(unit);if(unit.subject!==path.split('/')[1])err.push('subject no coincide con carpeta');if(err.length)throw Error(err.join('; '));if(this.units.some(u=>u.id===unit.id))throw Error(`ID duplicado ${unit.id}`);this.units.push(unit)}catch(e){this.errors.push(`${path}: ${e.message}`);const fallback=demoUnits.find(u=>path.endsWith(`/${u.id}.json`));if(fallback&&!this.units.some(u=>u.id===fallback.id))this.units.push(structuredClone(fallback))}}return this}
 forSubject(s){return this.units.filter(u=>u.subject===s).sort((a,b)=>(a.order??0)-(b.order??0))}
 unit(id){return this.units.find(u=>u.id===id)}
}
export class FutureAIContentProvider{async load(){throw Error('Proveedor IA sin implementar: el juego funciona solo con contenido local.')}}
export function validateUnit(u){const errors=[];if(!u||typeof u!=='object')return ['Se esperaba un objeto de unidad'];if(u.schemaVersion!==1)errors.push('schemaVersion debe ser 1');if(!slug.test(u.id||''))errors.push('id de unidad inválido');if(!SUBJECTS[u.subject])errors.push('subject desconocida');if(typeof u.title!=='string'||!u.title.trim())errors.push('title obligatorio');if(!Array.isArray(u.exercises)||u.exercises.length<4)errors.push('exercises necesita al menos 4 ejercicios para desbloquear al jefe');else{let ids=new Set();for(const [i,q] of u.exercises.entries()){const p=`ejercicio ${i+1}`;if(!slug.test(q.id||'')||ids.has(q.id))errors.push(`${p}: id inválido o duplicado`);ids.add(q.id);if(!TYPES.includes(q.type))errors.push(`${p}: type no admitido`);if(!slug.test(q.topic||''))errors.push(`${p}: topic obligatorio`);if(typeof q.question!=='string'||!q.question.trim())errors.push(`${p}: question obligatorio`);if(!Number.isInteger(q.difficulty)||q.difficulty<1||q.difficulty>5)errors.push(`${p}: difficulty entre 1 y 5`);if(typeof q.explanation!=='string'||!q.explanation.trim())errors.push(`${p}: explanation obligatoria`);if(!Array.isArray(q.tags))errors.push(`${p}: tags debe ser lista`);if(['multiple-choice','true-false'].includes(q.type)&&(!Array.isArray(q.options)||q.options.length<2||!q.options.includes(q.answer)))errors.push(`${p}: options/answer inválidos`);if(q.type==='numeric'&&(!Number.isFinite(q.answer)||q.tolerance!==undefined&&(!Number.isFinite(q.tolerance)||q.tolerance<0)))errors.push(`${p}: respuesta numérica/tolerancia inválida`);if(['short','written','predict-code','complete-code','debug-code','logic','puzzle','timed'].includes(q.type)&&(!q.rubric||!['exact','keywords','self-check'].includes(q.rubric.mode)))errors.push(`${p}: rúbrica explícita obligatoria`);if(q.rubric?.mode==='exact'&&(!Array.isArray(q.rubric.accepted)||!q.rubric.accepted.length))errors.push(`${p}: accepted obligatorio`);if(q.rubric?.mode==='keywords'&&(!Array.isArray(q.rubric.required)||!q.rubric.required.length))errors.push(`${p}: required obligatorio`);if(q.rubric?.mode==='self-check'&&typeof q.answer!=='string')errors.push(`${p}: modelo de respuesta obligatorio`);if(q.type==='timed'&&(!Number.isInteger(q.seconds)||q.seconds<10))errors.push(`${p}: seconds >= 10`);}}if(Array.isArray(u.exercises)&&u.exercises.filter(q=>q.rubric?.mode!=='self-check').length<4)errors.push('se requieren 4 ejercicios evaluables automáticamente');return errors}
