import {dayKey,clamp} from './config.js';
const fresh=()=>({attempts:0,correct:0,weighted:0,weight:0,items:{},days:{},last:0,streak:0,due:0,seconds:0,byType:{},byDifficulty:{},errors:[]});
export function record(s,unit,q,ok,seconds){const key=`${unit.subject}/${unit.id}/${q.topic}`,m=s.learn[key]??(s.learn[key]=fresh()),day=dayKey(),previous=m.items[q.id]||{};m.attempts++;m.correct+=Number(ok);m.last=Date.now();m.seconds+=seconds;m.days[day]=true;const bucket=m.byType[q.type]??(m.byType[q.type]={attempts:0,correct:0});bucket.attempts++;bucket.correct+=Number(ok);const diff=m.byDifficulty[q.difficulty]??(m.byDifficulty[q.difficulty]={attempts:0,correct:0});diff.attempts++;diff.correct+=Number(ok);
 // One scored encounter per item each day; weaker items resurface, but cannot be farmed in a loop.
 const qualified=previous.day!==day;const weight=qualified?Math.min(1.8,.6+q.difficulty*.24):0;if(weight){m.streak=ok?m.streak+1:0;m.weight+=weight;m.weighted+=ok?weight:0;m.items[q.id]={day,correct:ok,seen:(previous.seen||0)+1};const days=ok?clamp(1+Math.floor(m.streak/2),1,14):1;m.due=Date.now()+days*86400000}if(!ok)m.errors.unshift({id:q.id,at:Date.now(),question:q.question.slice(0,90)});m.errors=m.errors.slice(0,8);s.history.unshift({key,id:q.id,ok,seconds,difficulty:q.difficulty,time:Date.now(),qualified});s.history=s.history.slice(0,250);return {qualified,key,state:status(m)}}
export function status(m){if(!m||!m.attempts)return 'nuevo';const distinct=Object.keys(m.items).length,days=Object.keys(m.days).length,rate=m.weighted/Math.max(1,m.weight);if(m.attempts>=2&&rate<.55)return 'en recuperación';if(distinct>=5&&days>=2&&rate>=.84&&m.byDifficulty[2]?.correct>=2)return 'dominado';if(distinct>=3&&rate>=.7)return 'competente';return 'aprendiendo'}
export function mastery(s,unit){const qs=unit.exercises,topics=[...new Set(qs.map(q=>q.topic))];if(!topics.length)return {percent:0,topics:[]};const metrics=topics.map(t=>{const m=s.learn[`${unit.subject}/${unit.id}/${t}`],state=status(m),distinct=m?Object.keys(m.items).length:0,days=m?Object.keys(m.days).length:0,rate=m&&m.weight?m.weighted/m.weight:0;const confidence=clamp(distinct/5,0,1)*clamp(days/2,0,1);return {topic:t,state,percent:Math.round(rate*confidence*100),attempts:m?.attempts||0,errors:m?.errors||[]}});return {percent:Math.round(metrics.reduce((a,b)=>a+b.percent,0)/topics.length),topics:metrics}}
export function chooseQuestion(s,unit,{preferredType=null,exclude=[]}={}){let pool=unit.exercises.filter(q=>!exclude.includes(q.id));if(preferredType){const narrowed=pool.filter(q=>preferredType.includes(q.type));if(narrowed.length)pool=narrowed}if(!pool.length)return null;const now=Date.now(),day=dayKey();const scored=pool.map(q=>{const m=s.learn[`${unit.subject}/${unit.id}/${q.topic}`],seen=m?.items?.[q.id],fresh=seen?.day!==day,weak=m?.weight?1-m.weighted/m.weight:1,due=!m||m.due<=now;return {q,weight:(fresh?4:.15)+(due?3:0)+weak*4+(q.difficulty>1?1:0)+(m?.errors.some(e=>e.id===q.id)?2:0)+Math.random()*1.5}});scored.sort((a,b)=>b.weight-a.weight);return scored[0].q}
export function unitReady(s,unit){const p=s.progress[unit.id];return !!p&&p.attempts>=4&&p.correct>=Math.ceil(p.attempts*.6)&&unit.exercises.filter(q=>s.learn[`${unit.subject}/${unit.id}/${q.topic}`]?.items[q.id]).length>=4}
